name       : python-qstylizer
version    : 0.2.0
release    : 2
source     :
    - git|https://github.com/blambright/qstylizer : 0.2.0
homepage   : https://github.com/blambright/qstylizer
license    : MIT
component  : programming.python
summary    : Qt stylesheet generation utility for PyQt/PySide
description: |
    qstylizer is a python package designed to help with the construction of PyQt/PySide stylesheets.
builddeps  :
    - pbr
    - python-inflection
    - python-pytest-mock
    - python-tinycss2
rundeps    :
    - python-inflection
    - python-tinycss2
build      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    %python3_test pytest3 -v
